blank_issues_enabled: true
contact_links:
  - name: Security vulnerability
    url: https://github.com/atomic/http-kernel/security/policy
    about: Please report security issues via the Security Policy.
